### ISSUE TITLE
Conflict with BDMk22 Cockpit

### ISSUE THREAD

**Issue by gomker** [martinezfg11/AoA-Technologies#1]
First off,  Love your mod , its a must have for all my plane building.

I work on the BDAc mods and as I was helping update BDAMk22 I found that for some reason whenever I have AOA installed it causes the Internal IVA from BDAMk22 to not load. I tested on a clean install with minimal mods (AOA,BDA,Module Manager). Also , I see that my previous 1.13 version seems to have no conflict.

I looked at the MM patches and part names and internal spaces and cannot seem to find a reason why it would conflict. Wanted to see if I was missing something obvious with either part configuration.

This is the internal that has a conflict:
https://github.com/jrodrigv/BDMk22Plugin/blob/master/Distribution/GameData/BDMk22/Spaces/mk22Internal/internal.cfg

My testing was on 1.2.1 and your latest from GitHub.

Regards,

**Comment by martinezfg11** [comment]
Anything on the Output Log?

**Comment by gomker** [comment]
Only thing was the BDAMk22 part not finding the IVA

`[LOG 19:40:28.669] Cannot find InternalPart 'mk22Internal'
[ERR 19:40:28.669] Cannot add an InternalPart: Cannot find internal of name 'mk22Internal'`

It drove me mad because nothing had changed for the part config. Only DLL recompiles (and updates to the latest ASET/RPM) At first I thought It had to be RPM or ASET, but removing them had no effect.

**Comment by martinezfg11** [comment]
name = AoA.HornetInt
	MODEL
	{
		model = AoATech/Spaces/Hornet/model
		texture = CockpitGeneric, Squad/Spaces/sharedAssets/CockpitGeneric
		texture = CockpitGeneric_NRM, Squad/Spaces/sharedAssets/CockpitGeneric_NRM
	}

Doesn't seem like you have your model defined in your config.

**Comment by martinezfg11** [comment]
Needs to be 

name = mk22Internal

MODEL
{
     model = BDMk22/Spaces/mk22Internal/model
}

**Comment by gomker** [comment]
Tried that got a compile error as well

	[LOG 13:12:39.303] PartLoader: Compiling Internal Space 'BDMk22/Spaces/mk22Internal/internal/mk22Internal'
	[ERR 13:12:39.305] PartCompiler: Cannot clone model 'BDMk22/Spaces/model' as model does not exist

	[ERR 13:12:39.306] PartCompiler: Model was not compiled correctly

	[LOG 13:12:39.306] LoadInternalPart 'BDMk22/Spaces/mk22Internal/internal/mk22Internal' FAILED: Cannot find model`

I can get the IVA to load as the original config posted. But only if AOA is on the 1.13 version I had backed up.

**Comment by martinezfg11** [comment]
K I'll look into it when I get out of work.

**Comment by martinezfg11** [comment]
Remove everything in this directory - 
AoATech\Spaces\Tucano

Apparently it's been destroying all IVA's not just the BDARMORY ones

**Comment by martinezfg11** [comment]
Try the latest commit.

**Comment by gomker** [comment]
Looks to be working.
I have never seen anything like that before. Is this a KSP bug as well?  I would think that a part config should not be able to kill IVA like that.

**Comment by martinezfg11** [comment]
I only found out after looking at another github for the ASET pack. I guess I botched something during the .mu compilation.

**Comment by martinezfg11** [comment]
Closed c3d0d18
